[package]
name = "mmv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
mmove = { path = "lib/" }
clap = { version = "4.4.7", features = ["derive"] }
tempdir = "0.3.7"
